Cleaning up service install and removal

diff --git a/jpackage/resources/postinst b/jpackage/resources/postinst
--- a/jpackage/resources/postinst
+++ b/jpackage/resources/postinst
@@ -19,6 +19,8 @@ set -e
 # the debian-policy package
 
 
+echo "Handling $1 in postinst"
+
 case "$1" in
     configure)
     	adduser --system --quiet --shell /bin/false --home /opt/APPLICATION_PACKAGE \
@@ -27,8 +29,8 @@ case "$1" in
 		cp /opt/APPLICATION_PACKAGE/lib/app/APPLICATION_PACKAGE.service /usr/lib/systemd/system
 		chmod 644 /usr/lib/systemd/system/APPLICATION_PACKAGE.service
 		
-		mkdir -p $LOG_DIR
-		mkdir -p $TMP_DIR
+		[ -d $LOG_DIR ] || mkdir -p $LOG_DIR
+		[ -d $TMP_DIR ] || mkdir -p $TMP_DIR
 
 		dpkg-statoverride --update --add $FOP_USER $FOP_USER 4755 $LOG_DIR
 		dpkg-statoverride --update --add $FOP_USER $FOP_USER 4755 $TMP_DIR
@@ -42,9 +44,6 @@ case "$1" in
 		        fi
     		fi
 		done
-
-		deb-systemd-helper enable 'APPLICATION_PACKAGE.service'
-		deb-systemd-helper start 'APPLICATION_PACKAGE.service'
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -56,9 +55,24 @@ case "$1" in
     ;;
 esac
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
+	deb-systemd-helper unmask 'APPLICATION_PACKAGE.service' >/dev/null || true
+	
+	if deb-systemd-helper --quiet was-enabled 'APPLICATION_PACKAGE.service'; then
+		deb-systemd-helper enable 'APPLICATION_PACKAGE.service' >/dev/null || true
+	else
+		deb-systemd-helper update-state 'APPLICATION_PACKAGE.service' >/dev/null || true
+	fi
+	
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb_systemd_invoke $_dh_action 'APPLICATION_PACKAGE.service' >/dev/null || true
+	fi
+if
 
 exit 0
diff --git a/jpackage/resources/postrm b/jpackage/resources/postrm
--- a/jpackage/resources/postrm
+++ b/jpackage/resources/postrm
@@ -16,30 +16,50 @@ set -e
 # the debian-policy package
 
 
-case "$1" in
-    upgrade|failed-upgrade|abort-upgrade)
-		systemctl start APPLICATION_PACKAGE
-    ;;
+echo "Handling $1 in postrm"
 
-    purge|remove|abort-install|disappear)
-    	rm /usr/lib/systemd/system/APPLICATION_PACKAGE.service
-    	
-    	for i in /opt/APPLICATION_PACKAGE; do
-	    if dpkg-statoverride --list $i >/dev/null 2>&1; then
-		        dpkg-statoverride --remove $i
-		    fi
-		done
-    ;;
+if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
+	systemctrl --system daemon-reload >/dev/null || true
+fi
 
-    *)
-        echo "postrm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
+if [ "$1" = "remove" ]; then
+	if [ -x "/usr/bin/deb-systemd-helper" ]; then
+		deb-systemd-helper mask 'APPLICATION_PACKAGE.service' >/dev/null || true
+	fi
+fi
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
+if [ "$1" = "purge" ] ; then
+	if [ -x "/usr/bin/deb-systemd-helper" ]; then
+		deb-systemd-helper purge 'APPLICATION_PACKAGE.service' >/dev/null || true
+		deb-systemd-helper unmask 'APPLICATION_PACKAGE.service' >/dev/null || true
+	fi
 
-#DEBHELPER#
+	for i in /opt/APPLICATION_PACKAGE; do
+    if dpkg-statoverride --list $i >/dev/null 2>&1; then
+	        dpkg-statoverride --remove $i
+	    fi
+	done
+fi
 
-exit 0
+#case "$1" in
+#    upgrade|failed-upgrade|abort-upgrade)
+#		deb-systemd-helper start 'APPLICATION_PACKAGE.service' || true
+#    ;;
+#
+#    purge|remove|abort-install|disappear)
+#    	[ -f /usr/lib/systemd/system/APPLICATION_PACKAGE.service ] && rm /usr/lib/systemd/system/APPLICATION_PACKAGE.service
+#    	
+#    	for i in /opt/APPLICATION_PACKAGE; do
+#	    if dpkg-statoverride --list $i >/dev/null 2>&1; then
+#		        dpkg-statoverride --remove $i
+#		    fi
+#		done
+#    ;;
+
+#    *)
+#        echo "postrm called with unknown argument \`$1'" >&2
+#        exit 1
+#    ;;
+#esac
+
+#exit 0
diff --git a/jpackage/resources/prerm b/jpackage/resources/prerm
--- a/jpackage/resources/prerm
+++ b/jpackage/resources/prerm
@@ -14,28 +14,33 @@ set -e
 # the debian-policy package
 
 
-case "$1" in
-    upgrade)
-		deb-systemd-helper stop 'APPLICATION_PACKAGE.service'
-    ;;
+echo "Handling $1 in prem"
 
-    remove|deconfigure)
-		deb-systemd-helper stop 'APPLICATION_PACKAGE.service'
-		deb-systemd-helper disable 'APPLICATION_PACKAGE.service'
-    ;;
+if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
+	systemctl stop 'APPLICATION_PACKAGE.service' || true
+fi
 
-    failed-upgrade)
-    ;;
+if [ "$1" = "remove" ] && [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
+	deb-systemd-invoke stop 'APPLICATION_PACKAGE.service' >/dev/null || true
+fi
 
-    *)
-        echo "prerm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
+#case "$1" in
+#    upgrade)
+#		deb-systemd-helper stop 'APPLICATION_PACKAGE.service' || true
+#    ;;
+#
+#    remove|deconfigure)
+#		deb-systemd-helper stop 'APPLICATION_PACKAGE.service' || true
+#		deb-systemd-helper disable 'APPLICATION_PACKAGE.service' || true
+#    ;;
+#
+#    failed-upgrade)
+#    ;;
+#
+#    *)
+#        echo "prerm called with unknown argument \`$1'" >&2
+#        exit 1
+#    ;;
+#esac
 
 exit 0
