Setup linux service

diff --git a/jpackage/resources/postinst b/jpackage/resources/postinst
--- a/jpackage/resources/postinst
+++ b/jpackage/resources/postinst
@@ -1,6 +1,39 @@
 #!/bin/sh
 
-systemctl enable APPLICATION_PACKAGE
-systemctl start APPLICATION_PACKAGE
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+    	useradd --system --group --quiet --home /opt/%{name} \
+			--comment "User account for running the %{name}" fop-pdf-user
+		deb-systemd-helper enable 'fop-pdf-service.service'
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
